# Generated by Django 5.2.13 on 2026-04-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationinstance',
            name='course_csv_file',
            field=models.FileField(blank=True, null=True, upload_to='evaluations/course_csv/'),
        ),
        migrations.AddField(
            model_name='evaluationinstance',
            name='course_processed_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationinstance',
            name='course_total_respondents',
            field=models.IntegerField(default=0),
        ),
    ]
