# Generated by Django 4.2.23 on 2026-07-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_evaluationinstance_course_csv_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationinstance',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
    ]
