import React from 'react';
import { 
  Box, Container, Typography
} from '@mui/material';
import FacultyGlobalAIInsights from '../components/FacultyGlobalAIInsights';

const MyReports = () => {
  return (
    <Container maxWidth="xl">
      <Box sx={{ mb: 5 }}>
        <Typography variant="h3" fontWeight={800} gutterBottom sx={{ letterSpacing: '-0.02em' }}>
          My <span style={{ color: '#6366f1' }}>AI Insights</span>
        </Typography>
        <Typography variant="body1" color="text.secondary" sx={{ fontSize: '1.1rem', maxWidth: 800 }}>
          Your personalized career analysis generated by the Gemini Agentic System. 
          These insights synthesize student feedback and performance metrics across all your assigned courses.
        </Typography>
      </Box>

      <FacultyGlobalAIInsights />
      
      <Box sx={{ mt: 4, p: 4, borderRadius: 4, border: '1px dashed #e2e8f0', textAlign: 'center' }}>
        <Typography variant="body2" color="text.secondary">
          For detailed course reports and evaluation tables, please visit the <strong>Dashboard</strong>.
        </Typography>
      </Box>
    </Container>
  );
};

export default MyReports;
