# Generated by Django 5.2.13 on 2026-04-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('users', '0002_customuser_assigned_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='assigned_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.program'),
        ),
    ]
