# Generated by Django 5.2.13 on 2026-04-25 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=20, unique=True, verbose_name='short form')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='course code')),
                ('name', models.CharField(max_length=200, verbose_name='course name')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academic.program')),
            ],
            options={
                'unique_together': {('program', 'code')},
            },
        ),
        migrations.CreateModel(
            name='BatchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='batch code')),
                ('name', models.CharField(max_length=100, verbose_name='category name')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_categories', to='academic.program')),
            ],
            options={
                'verbose_name_plural': 'batch categories',
                'unique_together': {('program', 'code')},
            },
        ),
    ]
